### ISSUE TITLE
Handling resources

### ISSUE THREAD

**Issue by Tcholly** [Bigfoot71/Raymob#1]
Hi, sorry for the maybe stupid question but how can I handle resources such as texture or save files? Can I just put them in the project tree or do I have to bake them in the code or how else?

Thank you

**Comment by Bigfoot71** [comment]
# Answer

Everything works, with a few minor differences, as on PC.

### Loading Resources

To load resources, you need to place them in the `app\src\main\assets` directory, and you can load them directly.

For example, to load a file named `image.png` located in the `assets` directory, you just need to use `Texture2D tex = LoadTexture("image.png")`, and it will be loaded.

### File Writing/Loading

Regarding file writing/loading, you can use these basic functions in raylib:
1. `bool SaveFileData(const char *fileName, void *data, unsigned int bytesToWrite);`
2. `unsigned char *LoadFileData(const char *fileName, unsigned int *bytesRead);`

**But be careful**, if you use these functions, make sure to use them **after `InitWindow()`**, otherwise, the application may crash.

Alternatively, you can write your own file read/write functions that you can call whenever you want, even before `InitWindow()`. Here's a very basic example that you could use on PC/Android _(this only works for loading into the internal directory, it will not work for loading assets)_:
```c
#include <stdio.h>
#include "save.h"

Save saveData = {0};

bool SaveGame(void)
{
    #if defined(PLATFORM_ANDROID)
        const char* saveFilePath = TextFormat(
            "%s/%s", GetAndroidApp()->activity->internalDataPath, SAVE_FILE);
    #else
        const char* saveFilePath = TextFormat(
            "%s/%s", GetWorkingDirectory(), SAVE_FILE);    // NOTE: Useless on PC, just to copy the behavior of Android
    #endif

    FILE* file = fopen(saveFilePath, "wb");
    if (file == NULL) return false;

    fwrite(&saveData, sizeof(Save), 1, file);
    fclose(file);

    return true;
}

bool LoadGame(void)
{
    #if defined(PLATFORM_ANDROID)
        const char* saveFilePath = TextFormat(
            "%s/%s", GetAndroidApp()->activity->internalDataPath, SAVE_FILE);
    #else
        const char* saveFilePath = TextFormat(
            "%s/%s", GetWorkingDirectory(), SAVE_FILE);    // NOTE: Useless on PC, just to copy the behavior of Android
    #endif

    FILE* file = fopen(saveFilePath, "rb");
    if (file == NULL) return false;

    fread(&saveData, sizeof(Save), 1, file);
    fclose(file);

    return true;
}
```

# Explanation

With raylib on Android, you have two types of directories to remember (and this applies to all other types of applications as well).

You have the `assets` directory, which is managed by the Android AssetManager (on the raylib side), which is basically a compressed archive containing all the assets of your application. Therefore, you cannot write to the assets directory.

And you have the internal directory (which is not compressed) where you can write to, for example, game saves.

The AssetManager is initialized when your window is initialized, hence the risk of error I mentioned earlier. The `LoadFileData()` function on Android will call an overloaded function named `android_fopen` on the raylib side, which will first search for the requested file in the `assets` directory (unless the "w" mode is explicitly requested). If it is not found, it will then search in the internal directory.

That's why there is a risk of error if you call `LoadFileData()` while the AssetManager is not initialized. It will result in a mutex lock error with an invalid argument when attempting to search for the file via the AssetManager when it is not initialized.

_Hoping that this answers all your questions. If you have any further details you'd like me to address, please don't hesitate to ask, or feel free to close this issue._

**Comment by Tcholly** [comment]
Thank you very much, everything was crearly explained
