### ISSUE TITLE
API level

### ISSUE THREAD

**Issue by Bethleem** [Bigfoot71/raymob#25]
Not really an issue, but a doubt. You said raymob template targets APIs 24 to 33 and you can also adapt it to target other API versions if necessary. For higher API I have no problem, but what about lower API? I have been trying to target 19 to 33 and the apk won´t run even in android 6.0 (API 23). If I choose violence and target something like 19-24 instead 24-33, the apk fail to compile. There is some feature that prevents to go lower than 24?

**Comment by Bigfoot71** [comment]
No, nothing has been done to prevent this, indeed, and to be honest, the readme could use an update.  

If I remember correctly, I originally set the minimum API level to 24 due to a dependency in the project I was working on at the time, which eventually led to raymob. Back then, it seemed possible to target lower API levels with raylib alone.  

However, raylib has changed since then. I know some requirements for raylib on Android have evolved (about the NDK), and new features have been added to raymob. I'll need to review all of this and run some tests to update the readme.

I apologize for the confusion this may have caused you. I'm quite busy at the moment, but I hope to address this soon.

**Comment by Bigfoot71** [comment]
I started a redesign of raymob, and after a series of tests, I can confirm that the API targeting is already set to the broadest possible range (it was actually updated to API level 34). As a result, I also updated the README by removing the mention that the targeting could be adjusted.
