### ISSUE TITLE
Error Default activity not found

### ISSUE THREAD

**Issue by Nikolape** [Bigfoot71/raymob#27]
in gradle.properties with `app.category=DEFAULT` I get error Default activity not found
It only works with LAUNCHER

OS: Pop-os
Android Studio version: android-studio-2024.2.1.12-linux

**Comment by Bigfoot71** [comment]
Yes, this is normal if you downloaded the release. You need to create your activity yourself as follows:

https://github.com/user-attachments/assets/d958522a-3b75-4d3d-abf8-00847600f22f

**Comment by Bigfoot71** [comment]
Yes, this might not be very clear. You are apparently on the master branch, and this will be revised for the next release.

You can either use the current release version, or for the master branch, specify `LAUNCHER`. If you are confident in what you want to do, you can proceed as follows:

https://github.com/user-attachments/assets/882afeea-8009-47d7-9d2d-7aa79de4188d

I apologize in advance, there is a major update for raymob in the works, but due to personal time constraints, it has been delayed.

I will review the default configuration while completing these new features.

**Comment by Nikolape** [comment]
Thank you for your quick response.
