### ISSUE TITLE
how to compile main.cpp instead main.c?

### ISSUE THREAD

**Issue by svidaniya** [Bigfoot71/raymob#28]

**Comment by Bigfoot71** [comment]
If starting a new project without a CMake configuration, rename `main.c` to `main.cpp`. 

For existing configurations, clean and reconfigure the project. If new files were added, delete the `build` and `.cxx` directories and rebuild. 

To avoid future issues, adapt the main `CMakeLists.txt` to manually list source files instead of relying on its default automatic source detection, which is convenient initially but can become limiting later.

**Comment by svidaniya** [comment]
Is there a discord server or something like that for this specific repository?

**Comment by Bigfoot71** [comment]
> Is there a discord server or something like that for this specific repository?

No and I don't think it's worth it. But if you have a small issue, people can help you on the Android channel of raylib's discord

However, raymob is missing documentation, which I'll work on before the next release, but I'm short on time :/
