### ISSUE TITLE
Error when changing package name.

### ISSUE THREAD

**Issue by KorotkiyKamil** [Bigfoot71/Raymob#7]

**Comment by KorotkiyKamil** [comment]
Change app.name and projectName works.
app.application_id does not change.
app.application_id=com.raylib.raymob it works.
Or am I changing it in the wrong place?

![Снимок экрана 2023-12-01 183908](https://github.com/Bigfoot71/Raymob/assets/137780670/f8009e00-0ac9-45a4-bc09-b74d5d82f3f5)

**Comment by Bigfoot71** [comment]
@KorotkiyKamil Indeed, I apologize for the inconvenience. It's due to the addition of new features that haven't been fully tested...

I have just committed a fix for this issue (https://github.com/Bigfoot71/Raymob/commit/e8097a460d61c9642742ada4c69266eb42dbf76f). Could you please let me know if the current master branch resolves your issues?

**Comment by Bigfoot71** [comment]
@KorotkiyKamil Yes, that's normal. The name change occurs during compilation so that your APK/AAB has the requested package name. Afterward, the project is "reset".

It's the simplest way for the user _(and causes the fewest diverse issues)_ that I've found to centralize project configuration in a single file. _(Assuming it's well-maintained...)_

If the APK has the correct name, version, and requested features, and everything resets correctly in the raymob code _(meaning you can recompile again while changing names as needed)_, then you can consider everything to be working.

**Comment by KorotkiyKamil** [comment]
Ok.
Thank you.
