### ISSUE TITLE
i dont see Hint for raylib fonction

### ISSUE THREAD

**Issue by madhackademie** [Bigfoot71/Raymob#9]
i dont know if i should write in french or in english. My issues for now is that i dont see the "Hint" or tooltips who should appeare when whe make a mouse over like this one on visual studio https://i.imgur.com/CevOyJa.png. Did i miss something in the setup ? Je vous souhaite un joyeux noel et de bonnes fêtes de fin d'année.

**Comment by madhackademie** [comment]
ah and i see on there is an android gamme development Extention did you try it for raylib ?

**Comment by Bigfoot71** [comment]
@madhackademie It is preferable to communicate in English in case others come across this issue so that they can also understand.

Regarding your problem, it is not related to raymob but rather to the configuration of your IDE. If you can build and run the project, it means you have done everything correctly on the project side.

Look in the 'View' menu or in the settings of Android Studio; it should be enabled by default. You may have accidentally disabled it with a wrong key combination or something similar.

By the way, what do you mean about the Android game development extension?

Et merci, bonne fêtes de fin d'année à vous aussi :D

**Comment by madhackademie** [comment]
i did try to figure out in view and settings but i dont get any hint. i will ask on the discord if someone got any screen shot where i can check the option. And there is the link about adge https://developer.android.com/games/agde

**Comment by Bigfoot71** [comment]
Thanks for the link, I didn't know it. At first glance this doesn't seem contradictory to using raylib, and it also appears to use Gradle, so theoretically you should be able to use it for raymob as well.

**Comment by madhackademie** [comment]
i tryed to install this "add on" for 2 day but i fail miserably i m not rly familiard with sdn ndk cuz in untiy all was more easy. Any way i did find a way to reste the tooltip or hint https://i.imgur.com/g1xhhRe.png
